# Generated by Django 3.1.7 on 2021-04-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210419_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='question',
            field=models.ManyToManyField(related_query_name='question', to='app.Question'),
        ),
    ]
